CREATE TABLE [dbo].[Client] (
    [Id]                                  INT           IDENTITY (1, 1) NOT NULL,
    [Name]                                VARCHAR (50)  NOT NULL,
    [LastName]                            VARCHAR (50)  NOT NULL,
    [Gender]                              VARCHAR (10)  NULL,
    [Profession]                          VARCHAR (100) NULL,
    [Age]                                 SMALLINT      NULL,
    [DocumentType]                        VARCHAR (10)  NULL,
    [DocumentNumber]                      VARCHAR (20)  NULL,
    [Address]                             VARCHAR (100) NULL,
    [CellPhone]                           VARCHAR (20)  NULL,
    [Office]                              VARCHAR (50)  NULL,
    [City]                                VARCHAR (50)  NULL,
    [Department]                          VARCHAR (50)  NULL,
    [Country]                             VARCHAR (50)  NULL,
    [BirthDate]                           DATE          NULL,
    [PhoneNumber]                         VARCHAR (20)  NULL,
    [Email]                               VARCHAR (50)  NULL,
    [MonthlyIncome]                       BIGINT        NULL,
    [HasWorkedWithTourismIndustry]        BIT           CONSTRAINT [DF__Client__HasWorke__5AEE82B9] DEFAULT (CONVERT([bit],(0))) NULL,
    [TourismIndustry]                     VARCHAR (50)  NULL,
    [DebitCreditBanks]                    VARCHAR (100) NULL,
    [CoOwnerName]                         VARCHAR (50)  NULL,
    [CoOwnerLastName]                     VARCHAR (50)  NULL,
    [CoOwnerGender]                       VARCHAR (10)  NULL,
    [CoOwnerProfession]                   VARCHAR (100) NULL,
    [CoOwnerAge]                          SMALLINT      NULL,
    [CoOwnerDocumentType]                 VARCHAR (10)  NULL,
    [CoOwnerDocumentNumber]               VARCHAR (20)  NULL,
    [CoOwnerAddress]                      VARCHAR (100) NULL,
    [CoOwnerCellPhone]                    VARCHAR (20)  NULL,
    [CoOwnerOffice]                       VARCHAR (50)  NULL,
    [CoOwnerCity]                         VARCHAR (50)  NULL,
    [CoOwnerDepartment]                   VARCHAR (50)  NULL,
    [CoOwnerCountry]                      VARCHAR (50)  NULL,
    [CoOwnerBirthDate]                    DATE          NULL,
    [CoOwnerPhoneNumber]                  VARCHAR (20)  NULL,
    [CoOwnerEmail]                        VARCHAR (50)  NULL,
    [CoOwnerMonthlyIncome]                BIGINT        NULL,
    [CoOwnerHasWorkedWithTourismIndustry] BIT           NULL,
    [CoOwnerTourismIndustry]              VARCHAR (50)  NULL,
    [CoOwnerDebitCreditBanks]             VARCHAR (100) NULL,
    [MaritalStatus]                       VARCHAR (20)  NULL,
    [Sons]                                SMALLINT      NULL,
    [HousingType]                         VARCHAR (20)  NULL,
    [Neighborhood]                        VARCHAR (50)  NULL,
    [HasCar]                              BIT           NULL,
    [CarBrandModel]                       VARCHAR (50)  NULL,
    [Linner]                              VARCHAR (30)  NULL,
    [Closer]                              VARCHAR (30)  NULL,
    [TlmkCode]                            VARCHAR (30)  NULL,
    [Date]                                DATETIME      NOT NULL,
    [TableNumber]                         SMALLINT      NULL,
    [ArrivalTime]                         TIME (7)      NOT NULL,
    [WayOutTime]                          TIME (7)      NULL,
    [Signature]                           VARCHAR (MAX) NULL,
    [Voucher]                             VARCHAR (50)  NULL,
    [Observations]                        VARCHAR (MAX) NULL,
    [AttemptSell]                         BIT           NULL,
    [CreditDenied]                        BIT           NULL,
    [Reserve]                             BIT           NULL,
    [ReserveValue]                        BIGINT        NULL,
    CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED ([Id] ASC)
);

